name: Build and push image to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  Build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: docker push $IMAGE_TAG

  Run_tests:
    runs-on: ubuntu-latest
    container: $IMAGE_TAG
    needs: Build_and_push
    services:
      db:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Run tests
        run: |
          cd /var/kito