name: Build and push image to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_TAG: ghcr.io/{{ github.repository }}:{{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: docker push $IMAGE_TAG