name: Default workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  Build_image_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push $IMAGE_TAG

  Utests:
    needs: Build_image_and_push_to_registry
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    services:
      db:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POETRY_VIRTUALENVS_PATH: /root/.cache/pypoetry/virtualenvs

    steps:
      - name: Utests
        run: |
          cd /var/kito
          poetry run pytest

  Static_analysis:
    needs: Build_image_and_push_to_registry
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      POETRY_VIRTUALENVS_PATH: /root/.cache/pypoetry/virtualenvs

    steps:
      - name: Isort
        run: |
          cd /var/kito
          poetry run isort --check .

      - name: Black
        if: always()
        run: |
          cd /var/kito
          poetry run black --check .

      - name: Mypy
        if: always()
        run: |
          cd /var/kito
          poetry run mypy .

      - name: Flake8
        if: always()
        run: |
          cd /var/kito
          poetry run flake8 .

