name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Pull_image_from_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Image from ghcr.io
      run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}
  Run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:${{ github.sha }}
    services:
      db:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Run tests
        run: |
          cd /var/kito
          pytest
